/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.constraintsolver;

public class RoutingFilteredDecisionBuilder extends IntVarFilteredDecisionBuilder {
  private transient long swigCPtr;

  protected RoutingFilteredDecisionBuilder(long cPtr, boolean cMemoryOwn) {
    super(mainJNI.RoutingFilteredDecisionBuilder_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RoutingFilteredDecisionBuilder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mainJNI.delete_RoutingFilteredDecisionBuilder(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RoutingModel model() {
    long cPtr = mainJNI.RoutingFilteredDecisionBuilder_model(swigCPtr, this);
    return (cPtr == 0) ? null : new RoutingModel(cPtr, false);
  }

  public int getStartChainEnd(int vehicle) {
    return mainJNI.RoutingFilteredDecisionBuilder_getStartChainEnd(swigCPtr, this, vehicle);
  }

  public int getEndChainStart(int vehicle) {
    return mainJNI.RoutingFilteredDecisionBuilder_getEndChainStart(swigCPtr, this, vehicle);
  }

  public void makeDisjunctionNodesUnperformed(long node) {
    mainJNI.RoutingFilteredDecisionBuilder_makeDisjunctionNodesUnperformed(swigCPtr, this, node);
  }

  public void makeUnassignedNodesUnperformed() {
    mainJNI.RoutingFilteredDecisionBuilder_makeUnassignedNodesUnperformed(swigCPtr, this);
  }

}
