/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.constraintsolver;

public class SavingsFilteredDecisionBuilder extends RoutingFilteredDecisionBuilder {
  private transient long swigCPtr;

  protected SavingsFilteredDecisionBuilder(long cPtr, boolean cMemoryOwn) {
    super(mainJNI.SavingsFilteredDecisionBuilder_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SavingsFilteredDecisionBuilder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mainJNI.delete_SavingsFilteredDecisionBuilder(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  static public class SavingsParameters {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected SavingsParameters(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(SavingsParameters obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    @SuppressWarnings("deprecation")
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          mainJNI.delete_SavingsFilteredDecisionBuilder_SavingsParameters(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    public void setNeighbors_ratio(double value) {
      mainJNI.SavingsFilteredDecisionBuilder_SavingsParameters_neighbors_ratio_set(swigCPtr, this, value);
    }
  
    public double getNeighbors_ratio() {
      return mainJNI.SavingsFilteredDecisionBuilder_SavingsParameters_neighbors_ratio_get(swigCPtr, this);
    }
  
    public void setMax_memory_usage_bytes(double value) {
      mainJNI.SavingsFilteredDecisionBuilder_SavingsParameters_max_memory_usage_bytes_set(swigCPtr, this, value);
    }
  
    public double getMax_memory_usage_bytes() {
      return mainJNI.SavingsFilteredDecisionBuilder_SavingsParameters_max_memory_usage_bytes_get(swigCPtr, this);
    }
  
    public void setAdd_reverse_arcs(boolean value) {
      mainJNI.SavingsFilteredDecisionBuilder_SavingsParameters_add_reverse_arcs_set(swigCPtr, this, value);
    }
  
    public boolean getAdd_reverse_arcs() {
      return mainJNI.SavingsFilteredDecisionBuilder_SavingsParameters_add_reverse_arcs_get(swigCPtr, this);
    }
  
    public void setArc_coefficient(double value) {
      mainJNI.SavingsFilteredDecisionBuilder_SavingsParameters_arc_coefficient_set(swigCPtr, this, value);
    }
  
    public double getArc_coefficient() {
      return mainJNI.SavingsFilteredDecisionBuilder_SavingsParameters_arc_coefficient_get(swigCPtr, this);
    }
  
    public SavingsParameters() {
      this(mainJNI.new_SavingsFilteredDecisionBuilder_SavingsParameters(), true);
    }
  
  }

  public boolean buildSolution() {
    return mainJNI.SavingsFilteredDecisionBuilder_buildSolution(swigCPtr, this);
  }

}
