/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.constraintsolver;

public class SequentialSavingsFilteredDecisionBuilder extends SavingsFilteredDecisionBuilder {
  private transient long swigCPtr;

  protected SequentialSavingsFilteredDecisionBuilder(long cPtr, boolean cMemoryOwn) {
    super(mainJNI.SequentialSavingsFilteredDecisionBuilder_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SequentialSavingsFilteredDecisionBuilder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mainJNI.delete_SequentialSavingsFilteredDecisionBuilder(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public String toString() {
    return mainJNI.SequentialSavingsFilteredDecisionBuilder_toString(swigCPtr, this);
  }

}
