/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.util;

public class SortedDisjointIntervalList {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SortedDisjointIntervalList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SortedDisjointIntervalList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mainJNI.delete_SortedDisjointIntervalList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SortedDisjointIntervalList() {
    this(mainJNI.new_SortedDisjointIntervalList__SWIG_0(), true);
  }

  public SortedDisjointIntervalList(SWIGTYPE_p_std__vectorT_operations_research__ClosedInterval_t intervals) {
    this(mainJNI.new_SortedDisjointIntervalList__SWIG_1(SWIGTYPE_p_std__vectorT_operations_research__ClosedInterval_t.getCPtr(intervals)), true);
  }

  public SortedDisjointIntervalList(long[] starts, long[] ends) {
    this(mainJNI.new_SortedDisjointIntervalList__SWIG_2(starts, ends), true);
  }

  public SortedDisjointIntervalList(int[] starts, int[] ends) {
    this(mainJNI.new_SortedDisjointIntervalList__SWIG_3(starts, ends), true);
  }

  public SortedDisjointIntervalList buildComplementOnInterval(long start, long end) {
    return new SortedDisjointIntervalList(mainJNI.SortedDisjointIntervalList_buildComplementOnInterval(swigCPtr, this, start, end), true);
  }

  public SWIGTYPE_p_std__setT_operations_research__ClosedInterval_operations_research__SortedDisjointIntervalList__IntervalComparator_t__iterator insertInterval(long start, long end) {
    return new SWIGTYPE_p_std__setT_operations_research__ClosedInterval_operations_research__SortedDisjointIntervalList__IntervalComparator_t__iterator(mainJNI.SortedDisjointIntervalList_insertInterval(swigCPtr, this, start, end), true);
  }

  public void insertIntervals(long[] starts, long[] ends) {
    mainJNI.SortedDisjointIntervalList_insertIntervals__SWIG_0(swigCPtr, this, starts, ends);
  }

  public void insertIntervals(int[] starts, int[] ends) {
    mainJNI.SortedDisjointIntervalList_insertIntervals__SWIG_1(swigCPtr, this, starts, ends);
  }

  public int numIntervals() {
    return mainJNI.SortedDisjointIntervalList_numIntervals(swigCPtr, this);
  }

  public String toString() {
    return mainJNI.SortedDisjointIntervalList_toString(swigCPtr, this);
  }

}
